name: Building and Testing with GitHub Actions
on:
  push:
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./task2
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Set up JDK 15
        uses: actions/setup-java@v4
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build
        run: gradle build
      - name: Tests
        run: gradle test
      - name: Report test results
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          fail-on-failure: true
